version: '3.9'
services:
  db:
    image: mysql
    container_name: "comex-db-alura"
    restart: always
    environment:
      MYSQL_DATABASE: 'comex'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-database:/var/lib/mysql
volumes:
  my-database: